"""
gretil_kg_expander.py — Expand HPO Knowledge Graph to 500+ nodes
via GRETIL corpus parsing + generated concept nodes.

Sources:
  - GRETIL Sanskrit texts (Manusmṛti, Brahma Sūtras, Yoga Sūtras,
    Arthaśāstra, Mahābhārata sections, Upanishads)
  - Extended philosophical concepts from all 6 darśana traditions
  - Sub-concepts and derived concepts from base ontology

Run: python kg/gretil_kg_expander.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from kg.hpo_graph import HPOGraph, BASE, HPO

# ─────────────────────────────────────────────────────────────────
# EXTENDED CONCEPT TAXONOMY  (fills KG to 500+ nodes)
# ─────────────────────────────────────────────────────────────────

EXTENDED_CONCEPTS = [

    # ── METAPHYSICAL (Ātman, Brahman, Jīva, etc.) ───────────────
    {"id": "nirguna_brahman",  "label": "Nirguṇa Brahman",  "type": "MetaphysicalConcept",
     "sanskrit": "nirguṇa brahman", "schools": {"advaita": "endorsed"},
     "definition": "Brahman without qualities or attributes; the absolute formless reality according to Advaita Vedānta.",
     "source": "Māṇḍūkya Upaniṣad 7"},
    {"id": "saguna_brahman",   "label": "Saguṇa Brahman",   "type": "MetaphysicalConcept",
     "sanskrit": "saguṇa brahman", "schools": {"vishishtadvaita": "endorsed", "dvaita": "endorsed", "bhakti": "endorsed"},
     "definition": "Brahman with qualities; the personal God with divine attributes, worshipped devotionally.",
     "source": "Bhagavata Purāṇa 1.2.11"},
    {"id": "jiva",             "label": "Jīva",             "type": "MetaphysicalConcept",
     "sanskrit": "jīva", "schools": {"dvaita": "endorsed", "vishishtadvaita": "endorsed"},
     "definition": "The individual living soul, eternally distinct from Brahman in Dvaita; a mode of Brahman in Viśiṣṭādvaita.",
     "source": "Brahma Sūtras 2.3.17"},
    {"id": "maya",             "label": "Māyā",             "type": "MetaphysicalConcept",
     "sanskrit": "māyā", "schools": {"advaita": "endorsed", "dvaita": "rejected"},
     "definition": "The cosmic illusive power that superimposes apparent multiplicity on non-dual Brahman.",
     "source": "Māṇḍūkya Kārikā 1.16"},
    {"id": "avidya",           "label": "Avidyā",           "type": "MetaphysicalConcept",
     "sanskrit": "avidyā", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "Ignorance of the true nature of the self; the root cause of bondage and suffering.",
     "source": "Vivekacūḍāmaṇi 140"},
    {"id": "prakriti",         "label": "Prakṛti",          "type": "MetaphysicalConcept",
     "sanskrit": "prakṛti", "schools": {"vishishtadvaita": "endorsed", "dvaita": "endorsed"},
     "definition": "Primordial matter or nature; the material cause of the universe, containing three guṇas.",
     "source": "Sāṅkhya Kārikā 3"},
    {"id": "purusha",          "label": "Puruṣa",           "type": "MetaphysicalConcept",
     "sanskrit": "puruṣa", "schools": {"nyaya": "endorsed", "vishishtadvaita": "endorsed"},
     "definition": "Pure consciousness, the eternal witness; in Sāṅkhya, the transcendent self distinct from Prakṛti.",
     "source": "Sāṅkhya Kārikā 19"},
    {"id": "ishvara",          "label": "Īśvara",           "type": "MetaphysicalConcept",
     "sanskrit": "īśvara", "schools": {"dvaita": "endorsed", "vishishtadvaita": "endorsed", "nyaya": "endorsed", "advaita": "neutral"},
     "definition": "The personal God as supreme ruler; in Advaita, Īśvara is Brahman as seen through māyā.",
     "source": "Yoga Sūtras 1.24"},
    {"id": "lila",             "label": "Līlā",             "type": "MetaphysicalConcept",
     "sanskrit": "līlā", "schools": {"bhakti": "endorsed", "vishishtadvaita": "endorsed"},
     "definition": "Divine play; the spontaneous, joyful activity of the supreme being with no ulterior motive.",
     "source": "Bhagavata Purāṇa 10.33.36"},
    {"id": "samsara",          "label": "Saṃsāra",          "type": "MetaphysicalConcept",
     "sanskrit": "saṃsāra", "schools": {"advaita": "endorsed", "dvaita": "endorsed", "nyaya": "endorsed"},
     "definition": "The cycle of birth, death and rebirth governed by karma; the conditioned existence.",
     "source": "Bhagavad Gīṭā 9.3"},
    {"id": "pralaya",          "label": "Pralaya",          "type": "MetaphysicalConcept",
     "sanskrit": "pralaya", "schools": {"vishishtadvaita": "endorsed"},
     "definition": "Cosmic dissolution at the end of a kalpa, when all manifested existence returns to its unmanifest state.",
     "source": "Bhagavad Gītā 8.17-19"},
    {"id": "avatar",           "label": "Avatāra",          "type": "MetaphysicalConcept",
     "sanskrit": "avatāra", "schools": {"bhakti": "endorsed", "vishishtadvaita": "endorsed", "dvaita": "endorsed"},
     "definition": "Divine descent; the direct manifestation of the supreme being in a specific form to restore dharma.",
     "source": "Bhagavad Gītā 4.7-8"},
    {"id": "vishesa",          "label": "Viśeṣa",           "type": "MetaphysicalConcept",
     "sanskrit": "viśeṣa", "schools": {"dvaita": "endorsed"},
     "definition": "The doctrine of absolute difference; in Dvaita, five fundamental distinctions between Īśvara, jīvas, and world.",
     "source": "Madhvācārya's Anuvyākhyāna"},
    {"id": "suddhadvaita",     "label": "Śuddhādvaita",     "type": "MetaphysicalConcept",
     "sanskrit": "śuddhādvaita", "schools": {"bhakti": "endorsed"},
     "definition": "Pure non-dualism; Vallabhācārya's school claiming the world is real and a pure manifestation of Brahman-Kṛṣṇa.",
     "source": "Vallabhācārya's Anubhāṣya"},
    {"id": "acintya_bhedabheda","label": "Acintya Bhedābheda","type": "MetaphysicalConcept",
     "sanskrit": "acintya bhedābheda", "schools": {"bhakti": "endorsed"},
     "definition": "Inconceivable simultaneous difference and non-difference; Caitanya's Vaiṣṇava Vedānta.",
     "source": "Caitanya Caritāmṛta 2.8.281"},

    # ── EPISTEMOLOGY (Pramāṇa) ───────────────────────────────────
    {"id": "sabda",            "label": "Śabda",            "type": "EpistemicConcept",
     "sanskrit": "śabda", "schools": {"mimamsa": "endorsed", "advaita": "endorsed"},
     "definition": "Verbal testimony, especially Vedic scripture, as a valid means of knowledge.",
     "source": "Nyāya Sūtras 1.1.7"},
    {"id": "upamana",          "label": "Upamāna",          "type": "EpistemicConcept",
     "sanskrit": "upamāna", "schools": {"nyaya": "endorsed"},
     "definition": "Comparison or analogy as a means of knowing an unfamiliar object through its similarity to a familiar one.",
     "source": "Nyāya Sūtras 1.1.6"},
    {"id": "arthapatti",       "label": "Arthāpatti",       "type": "EpistemicConcept",
     "sanskrit": "arthāpatti", "schools": {"mimamsa": "endorsed"},
     "definition": "Postulation or presumption; knowing something unstated that explains an apparent contradiction.",
     "source": "Kumārila Bhaṭṭa's Ślokavārttika"},
    {"id": "anupalabdhi",      "label": "Anupalabdhi",      "type": "EpistemicConcept",
     "sanskrit": "anupalabdhi", "schools": {"mimamsa": "endorsed", "advaita": "endorsed"},
     "definition": "Non-cognition or absence; knowing the absence of something by its non-perception.",
     "source": "Prabhākara's Bṛhatī"},
    {"id": "vyapti",           "label": "Vyāpti",           "type": "EpistemicConcept",
     "sanskrit": "vyāpti", "schools": {"nyaya": "endorsed"},
     "definition": "Universal concomitance; the invariable relation between hetu (reason) and sādhya (probandum) in inference.",
     "source": "Nyāya Sūtras 1.1.5"},
    {"id": "pratyaksha",       "label": "Pratyakṣa",        "type": "EpistemicConcept",
     "sanskrit": "pratyakṣa", "schools": {"nyaya": "endorsed", "mimamsa": "endorsed"},
     "definition": "Direct perception through the sense organs; the most immediate of the valid means of knowledge.",
     "source": "Nyāya Sūtras 1.1.4"},
    {"id": "anumana",          "label": "Anumāna",          "type": "EpistemicConcept",
     "sanskrit": "anumāna", "schools": {"nyaya": "endorsed"},
     "definition": "Inference from observed signs; requires vyāpti (universal concomitance) and pakṣa (the subject).",
     "source": "Nyāya Sūtras 1.1.5"},
    {"id": "yukti",            "label": "Yukti",            "type": "EpistemicConcept",
     "sanskrit": "yukti", "schools": {"nyaya": "endorsed", "advaita": "endorsed"},
     "definition": "Logical reasoning or fitness; the use of reasoned argument to determine what is appropriate.",
     "source": "Caraka Saṃhitā Vimāna 8.27"},
    {"id": "svatah_pramanya",  "label": "Svataḥ Prāmāṇya", "type": "EpistemicConcept",
     "sanskrit": "svataḥ prāmāṇya", "schools": {"mimamsa": "endorsed"},
     "definition": "Self-validity of knowledge; Mīmāṃsā doctrine that valid cognition carries its own validity intrinsically.",
     "source": "Śābara Bhāṣya on Mīmāṃsā Sūtras"},
    {"id": "paratah_pramanya", "label": "Parataḥ Prāmāṇya","type": "EpistemicConcept",
     "sanskrit": "parataḥ prāmāṇya", "schools": {"nyaya": "endorsed"},
     "definition": "Extrinsic validity; Nyāya view that the validity of cognition depends on external corroborating factors.",
     "source": "Vātsyāyana's Bhāṣya on Nyāya Sūtras"},

    # ── ETHICS (Dharma, Karma, Yama–Niyama) ─────────────────────
    {"id": "ahimsa",           "label": "Ahiṃsā",           "type": "EthicalConcept",
     "sanskrit": "ahiṃsā", "schools": {"advaita": "endorsed", "bhakti": "endorsed", "nyaya": "endorsed"},
     "definition": "Non-violence; non-injury to all living beings in thought, word and deed.",
     "source": "Yoga Sūtras 2.30"},
    {"id": "satya",            "label": "Satya",            "type": "EthicalConcept",
     "sanskrit": "satya", "schools": {"nyaya": "endorsed", "advaita": "endorsed"},
     "definition": "Truthfulness; speaking only what is true, wholesome, and beneficial.",
     "source": "Yoga Sūtras 2.30"},
    {"id": "asteya",           "label": "Asteya",           "type": "EthicalConcept",
     "sanskrit": "asteya", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "Non-stealing; refraining from taking what is not given, in any form.",
     "source": "Yoga Sūtras 2.30"},
    {"id": "brahmacharya",     "label": "Brahmacarya",      "type": "EthicalConcept",
     "sanskrit": "brahmacarya", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "Celibacy and moderation of the senses; directing vital energy toward Brahman-realization.",
     "source": "Yoga Sūtras 2.30"},
    {"id": "aparigraha",       "label": "Aparigraha",       "type": "EthicalConcept",
     "sanskrit": "aparigraha", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "Non-possessiveness; not grasping beyond what is needed for one's sustenance and practice.",
     "source": "Yoga Sūtras 2.30"},
    {"id": "shaucha",          "label": "Śauca",            "type": "EthicalConcept",
     "sanskrit": "śauca", "schools": {"all": "endorsed"},
     "definition": "Purity — external (bodily cleanliness) and internal (mental purity); first niyama.",
     "source": "Yoga Sūtras 2.32"},
    {"id": "santosha",         "label": "Santoṣa",          "type": "EthicalConcept",
     "sanskrit": "santoṣa", "schools": {"advaita": "endorsed", "bhakti": "endorsed"},
     "definition": "Contentment with what one has; equanimity regardless of external circumstances.",
     "source": "Yoga Sūtras 2.32"},
    {"id": "svadhyaya",        "label": "Svādhyāya",        "type": "EthicalConcept",
     "sanskrit": "svādhyāya", "schools": {"mimamsa": "endorsed", "advaita": "endorsed"},
     "definition": "Self-study; study of sacred scriptures and reflection on one's own nature.",
     "source": "Yoga Sūtras 2.32"},
    {"id": "ishvara_pranidhana","label":"Īśvara Praṇidhāna","type": "EthicalConcept",
     "sanskrit": "īśvara praṇidhāna", "schools": {"bhakti": "endorsed", "vishishtadvaita": "endorsed"},
     "definition": "Surrender to God; dedicating all actions and their fruits to the supreme being.",
     "source": "Yoga Sūtras 2.32"},
    {"id": "dana",             "label": "Dāna",             "type": "EthicalConcept",
     "sanskrit": "dāna", "schools": {"mimamsa": "endorsed", "bhakti": "endorsed", "dvaita": "endorsed"},
     "definition": "Charity and giving; one of the three pillars of dharmic life along with tapas and yajña.",
     "source": "Bhagavad Gītā 16.1-3"},
    {"id": "tapas",            "label": "Tapas",            "type": "EthicalConcept",
     "sanskrit": "tapas", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "Austerity and self-discipline; generating inner heat through spiritual practice.",
     "source": "Yoga Sūtras 2.32"},
    {"id": "daya",             "label": "Dayā",             "type": "EthicalConcept",
     "sanskrit": "dayā", "schools": {"bhakti": "endorsed", "advaita": "endorsed"},
     "definition": "Compassion; feeling the suffering of others as one's own and acting to relieve it.",
     "source": "Mahābhārata Śānti Parva 167.9"},
    {"id": "titiksha",         "label": "Titikṣā",         "type": "EthicalConcept",
     "sanskrit": "titikṣā", "schools": {"advaita": "endorsed"},
     "definition": "Forbearance; enduring heat and cold, pleasure and pain without complaint or retaliation.",
     "source": "Vivekacūḍāmaṇi 23"},
    {"id": "kshama",           "label": "Kṣamā",           "type": "EthicalConcept",
     "sanskrit": "kṣamā", "schools": {"bhakti": "endorsed", "advaita": "endorsed"},
     "definition": "Forgiveness; releasing resentment toward those who have caused harm.",
     "source": "Mahābhārata Udyoga Parva 33.60"},

    # ── SOTERIOLOGY (Mokṣa paths) ───────────────────────────────
    {"id": "jnana_yoga",       "label": "Jñāna Yoga",       "type": "SoteriologicalConcept",
     "sanskrit": "jñāna yoga", "schools": {"advaita": "endorsed"},
     "definition": "The path of knowledge; liberation through direct discrimination between the real and unreal.",
     "source": "Bhagavad Gītā Chapter 4"},
    {"id": "bhakti_yoga",      "label": "Bhakti Yoga",      "type": "SoteriologicalConcept",
     "sanskrit": "bhakti yoga", "schools": {"bhakti": "endorsed", "vishishtadvaita": "endorsed", "dvaita": "endorsed"},
     "definition": "The path of devotion; liberation through loving surrender to the personal God.",
     "source": "Bhagavad Gītā Chapter 12"},
    {"id": "raja_yoga",        "label": "Rāja Yoga",        "type": "SoteriologicalConcept",
     "sanskrit": "rāja yoga", "schools": {"nyaya": "endorsed"},
     "definition": "The royal path; liberation through the eight limbs (ashtānga) of Patañjali's Yoga system.",
     "source": "Yoga Sūtras 2.29"},
    {"id": "karma_yoga",       "label": "Karma Yoga",       "type": "SoteriologicalConcept",
     "sanskrit": "karma yoga", "schools": {"mimamsa": "endorsed", "advaita": "endorsed", "dvaita": "endorsed"},
     "definition": "Action without attachment to fruits; performing one's duty as an offering to God.",
     "source": "Bhagavad Gītā 3.5-9"},
    {"id": "prapatti",         "label": "Prapatti",         "type": "SoteriologicalConcept",
     "sanskrit": "prapatti", "schools": {"vishishtadvaita": "endorsed", "dvaita": "endorsed"},
     "definition": "Total self-surrender to God as an independent means of liberation.",
     "source": "Rāmānuja's Gadyatrayam"},
    {"id": "samadhi",          "label": "Samādhi",          "type": "SoteriologicalConcept",
     "sanskrit": "samādhi", "schools": {"nyaya": "endorsed", "advaita": "endorsed"},
     "definition": "Absorption; the final limb of yoga where the mind is fully absorbed in its object.",
     "source": "Yoga Sūtras 3.3"},
    {"id": "nirvikalpa_samadhi","label": "Nirvikalpa Samādhi","type": "SoteriologicalConcept",
     "sanskrit": "nirvikalpa samādhi", "schools": {"advaita": "endorsed"},
     "definition": "Absorption without cognitive modification; pure undifferentiated awareness.",
     "source": "Vivekacūḍāmaṇi 339"},
    {"id": "savikalpa_samadhi","label": "Savikalpa Samādhi","type": "SoteriologicalConcept",
     "sanskrit": "savikalpa samādhi", "schools": {"nyaya": "endorsed", "advaita": "endorsed"},
     "definition": "Absorption with object; superconscious state retaining awareness of the meditator-object distinction.",
     "source": "Yoga Sūtras 1.41"},
    {"id": "videha_mukti",     "label": "Videha Mukti",     "type": "SoteriologicalConcept",
     "sanskrit": "videha mukti", "schools": {"advaita": "endorsed"},
     "definition": "Disembodied liberation; liberation attained after the fall of the physical body.",
     "source": "Brahma Sūtras 4.1.15"},
    {"id": "jivanmukti",       "label": "Jīvanmukti",       "type": "SoteriologicalConcept",
     "sanskrit": "jīvanmukti", "schools": {"advaita": "endorsed"},
     "definition": "Liberation while living; continuing to act in the world without bondage after Self-realization.",
     "source": "Jīvanmuktiviveka of Vidyāraṇya"},
    {"id": "sayujya",          "label": "Sāyujya",          "type": "SoteriologicalConcept",
     "sanskrit": "sāyujya", "schools": {"bhakti": "endorsed", "advaita": "endorsed"},
     "definition": "Union with God; the highest of the four types of liberation in bhakti traditions.",
     "source": "Bhāgavata Purāṇa 3.29.13"},
    {"id": "salokya",          "label": "Sālokya",          "type": "SoteriologicalConcept",
     "sanskrit": "sālokya", "schools": {"bhakti": "endorsed", "dvaita": "endorsed"},
     "definition": "Dwelling in the same realm as God; liberation as abiding in Vaikuṇṭha.",
     "source": "Bhāgavata Purāṇa 3.29.13"},

    # ── PSYCHOLOGY & MIND ────────────────────────────────────────
    {"id": "chitta",           "label": "Citta",            "type": "PsychologicalConcept",
     "sanskrit": "citta", "schools": {"nyaya": "endorsed", "advaita": "endorsed"},
     "definition": "Mind-stuff or consciousness; the mental field that receives and processes experience.",
     "source": "Yoga Sūtras 1.2"},
    {"id": "vritti",           "label": "Vṛtti",            "type": "PsychologicalConcept",
     "sanskrit": "vṛtti", "schools": {"nyaya": "endorsed"},
     "definition": "Mental modification or wave; the fluctuations of mind that yoga aims to still.",
     "source": "Yoga Sūtras 1.6"},
    {"id": "vasana",           "label": "Vāsanā",           "type": "PsychologicalConcept",
     "sanskrit": "vāsanā", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "Latent subliminal impression; unconscious tendency formed by past experience driving future action.",
     "source": "Yoga Sūtras 4.24"},
    {"id": "samskara",         "label": "Saṃskāra",         "type": "PsychologicalConcept",
     "sanskrit": "saṃskāra", "schools": {"nyaya": "endorsed", "advaita": "endorsed"},
     "definition": "Mental imprint left by past actions and experiences; drives habitual tendencies.",
     "source": "Yoga Sūtras 1.50"},
    {"id": "ahankara",         "label": "Ahaṃkāra",         "type": "PsychologicalConcept",
     "sanskrit": "ahaṃkāra", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "The ego or I-maker; the faculty that creates the sense of individual separate identity.",
     "source": "Sāṅkhya Kārikā 24"},
    {"id": "buddhi",           "label": "Buddhi",           "type": "PsychologicalConcept",
     "sanskrit": "buddhi", "schools": {"nyaya": "endorsed", "advaita": "endorsed"},
     "definition": "Intellect or discriminative faculty; the aspect of mind that determines, judges, and discriminates.",
     "source": "Sāṅkhya Kārikā 23"},
    {"id": "manas",            "label": "Manas",            "type": "PsychologicalConcept",
     "sanskrit": "manas", "schools": {"nyaya": "endorsed"},
     "definition": "The lower mind; receives sense-data and coordinates the sense and motor organs.",
     "source": "Sāṅkhya Kārikā 27"},
    {"id": "kama",             "label": "Kāma",             "type": "PsychologicalConcept",
     "sanskrit": "kāma", "schools": {"mimamsa": "endorsed"},
     "definition": "Desire; one of the four purushārthas, the legitimate pursuit of pleasure and love.",
     "source": "Kāma Sūtras 1.2.1"},
    {"id": "krodha",           "label": "Krodha",           "type": "PsychologicalConcept",
     "sanskrit": "krodha", "schools": {"advaita": "endorsed"},
     "definition": "Anger; arising from thwarted desire; causes delusion, loss of memory, and destruction of reason.",
     "source": "Bhagavad Gītā 2.62-63"},
    {"id": "lobha",            "label": "Lobha",            "type": "PsychologicalConcept",
     "sanskrit": "lobha", "schools": {"advaita": "endorsed"},
     "definition": "Greed; excessive desire for more than one's due; a root cause of adharma.",
     "source": "Mahābhārata Śānti Parva 90.15"},
    {"id": "moha",             "label": "Moha",             "type": "PsychologicalConcept",
     "sanskrit": "moha", "schools": {"advaita": "endorsed"},
     "definition": "Delusion; confusion about the nature of reality arising from avidyā.",
     "source": "Bhagavad Gītā 18.73"},
    {"id": "viveka",           "label": "Viveka",           "type": "PsychologicalConcept",
     "sanskrit": "viveka", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "Discrimination; the faculty to distinguish between the real (Brahman) and the unreal (world).",
     "source": "Vivekacūḍāmaṇi 19"},
    {"id": "vairagya",         "label": "Vairāgya",         "type": "PsychologicalConcept",
     "sanskrit": "vairāgya", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "Dispassion; turning away from enjoyment of perceived and scriptural pleasures.",
     "source": "Yoga Sūtras 1.12"},
    {"id": "mumukshutva",      "label": "Mumukṣutva",       "type": "PsychologicalConcept",
     "sanskrit": "mumukṣutva", "schools": {"advaita": "endorsed"},
     "definition": "Intense desire for liberation; one of the four qualifications (sādhana-catuṣṭaya) for Vedāntic study.",
     "source": "Vivekacūḍāmaṇi 27"},
    {"id": "shradha",          "label": "Śraddhā",          "type": "PsychologicalConcept",
     "sanskrit": "śraddhā", "schools": {"bhakti": "endorsed", "advaita": "endorsed"},
     "definition": "Faith; trust in the teacher, scripture, and the self grounded in intuitive conviction.",
     "source": "Bhagavad Gītā 17.3"},

    # ── COSMOLOGY ────────────────────────────────────────────────
    {"id": "srsti",            "label": "Sṛṣṭi",            "type": "CosmologicalConcept",
     "sanskrit": "sṛṣṭi", "schools": {"vishishtadvaita": "endorsed", "dvaita": "endorsed"},
     "definition": "Creation or emanation; the process by which the universe is projected from Brahman.",
     "source": "Taittirīya Upaniṣad 2.1.1"},
    {"id": "sthiti",           "label": "Sthiti",           "type": "CosmologicalConcept",
     "sanskrit": "sthiti", "schools": {"vishishtadvaita": "endorsed"},
     "definition": "Sustenance or preservation; the aspect of Brahman/Viṣṇu that maintains the created universe.",
     "source": "Bhagavata Purāṇa 1.2.23"},
    {"id": "samhara",          "label": "Saṃhāra",          "type": "CosmologicalConcept",
     "sanskrit": "saṃhāra", "schools": {"vishishtadvaita": "endorsed"},
     "definition": "Dissolution or reabsorption; the universe returning to its unmanifest state in Brahman.",
     "source": "Bhagavad Gītā 9.7"},
    {"id": "pancha_kosha",     "label": "Pañca Kośa",       "type": "CosmologicalConcept",
     "sanskrit": "pañca kośa", "schools": {"advaita": "endorsed"},
     "definition": "The five sheaths (anna, prāṇa, manas, vijñāna, ānanda) that veil the pure self.",
     "source": "Taittirīya Upaniṣad 2.1-5"},
    {"id": "pancha_bhuta",     "label": "Pañca Bhūta",      "type": "CosmologicalConcept",
     "sanskrit": "pañca bhūta", "schools": {"nyaya": "endorsed", "vishishtadvaita": "endorsed"},
     "definition": "The five gross elements: earth (pṛthvī), water (āp), fire (tejas), air (vāyu), space (ākāśa).",
     "source": "Taittirīya Upaniṣad 2.1.1"},
    {"id": "trigunas",         "label": "Triguṇas",         "type": "CosmologicalConcept",
     "sanskrit": "triguṇas", "schools": {"vishishtadvaita": "endorsed", "advaita": "endorsed"},
     "definition": "Three qualities of Prakṛti: sattva (purity), rajas (activity), tamas (inertia).",
     "source": "Bhagavad Gītā 14.5"},
    {"id": "sattva",           "label": "Sattva",           "type": "CosmologicalConcept",
     "sanskrit": "sattva", "schools": {"all": "endorsed"},
     "definition": "The quality of purity, clarity, and harmony; the guṇa most conducive to liberation.",
     "source": "Bhagavad Gītā 14.6"},
    {"id": "rajas",            "label": "Rajas",            "type": "CosmologicalConcept",
     "sanskrit": "rajas", "schools": {"all": "endorsed"},
     "definition": "The quality of activity, passion, and restlessness; binds through attachment to action.",
     "source": "Bhagavad Gītā 14.7"},
    {"id": "tamas",            "label": "Tamas",            "type": "CosmologicalConcept",
     "sanskrit": "tamas", "schools": {"all": "endorsed"},
     "definition": "The quality of inertia, dullness, and ignorance; binds through heedlessness and sleep.",
     "source": "Bhagavad Gītā 14.8"},

    # ── SOCIAL / DHARMAŚĀSTRA ────────────────────────────────────
    {"id": "varnashrama",      "label": "Varṇāśrama",       "type": "SocialConcept",
     "sanskrit": "varṇāśrama", "schools": {"mimamsa": "endorsed", "dvaita": "endorsed"},
     "definition": "The four social orders (varṇa) and four life stages (āśrama) structuring dharmic society.",
     "source": "Manusmṛti 1.87-91"},
    {"id": "brahmin_dharma",   "label": "Brāhmaṇa Dharma",  "type": "SocialConcept",
     "sanskrit": "brāhmaṇa dharma", "schools": {"mimamsa": "endorsed"},
     "definition": "Duties of the priestly class: teaching, studying, performing and officiating sacrifices, giving and receiving gifts.",
     "source": "Manusmṛti 1.88"},
    {"id": "kshatriya_dharma", "label": "Kṣatriya Dharma",  "type": "SocialConcept",
     "sanskrit": "kṣatriya dharma", "schools": {"mimamsa": "endorsed", "dvaita": "endorsed"},
     "definition": "Duties of the warrior-ruler class: protection of subjects, battle, governance, justice.",
     "source": "Manusmṛti 1.89"},
    {"id": "vaishya_dharma",   "label": "Vaiśya Dharma",    "type": "SocialConcept",
     "sanskrit": "vaiśya dharma", "schools": {"mimamsa": "endorsed"},
     "definition": "Duties of the merchant-farmer class: agriculture, cattle-rearing, trade.",
     "source": "Manusmṛti 1.90"},
    {"id": "shudra_dharma",    "label": "Śūdra Dharma",     "type": "SocialConcept",
     "sanskrit": "śūdra dharma", "schools": {"mimamsa": "endorsed"},
     "definition": "Duties of the serving class: service to the other three varṇas without envy.",
     "source": "Manusmṛti 1.91"},
    {"id": "brahmacharya_ashrama","label":"Brahmacaryāśrama","type": "SocialConcept",
     "sanskrit": "brahmacaryāśrama", "schools": {"mimamsa": "endorsed"},
     "definition": "The student stage; from initiation (upanayana) through study under a guru.",
     "source": "Manusmṛti 2.36-38"},
    {"id": "grihastha_ashrama","label": "Gṛhasthāśrama",    "type": "SocialConcept",
     "sanskrit": "gṛhasthāśrama", "schools": {"mimamsa": "endorsed"},
     "definition": "The householder stage; the source of all four aims of life and support for other āśramas.",
     "source": "Manusmṛti 3.77-78"},
    {"id": "vanaprastha_ashrama","label":"Vānaprasthāśrama","type": "SocialConcept",
     "sanskrit": "vānaprasthāśrama", "schools": {"advaita": "endorsed", "mimamsa": "endorsed"},
     "definition": "The forest-dweller stage; gradual withdrawal from household duties for contemplation.",
     "source": "Manusmṛti 6.1-3"},
    {"id": "sannyasa_ashrama", "label": "Sannyāsāśrama",    "type": "SocialConcept",
     "sanskrit": "sannyāsāśrama", "schools": {"advaita": "endorsed"},
     "definition": "The renunciate stage; complete renunciation of worldly life for single-pointed pursuit of mokṣa.",
     "source": "Manusmṛti 6.33-35"},
    {"id": "raja_dharma",      "label": "Rājadharma",       "type": "SocialConcept",
     "sanskrit": "rājadharma", "schools": {"mimamsa": "endorsed"},
     "definition": "The duties of the king; governance based on dharma including dandanīti (polity), kosha (treasury), sena (army).",
     "source": "Mahābhārata Śānti Parva 56-130"},
    {"id": "danda_niti",       "label": "Daṇḍanīti",        "type": "SocialConcept",
     "sanskrit": "daṇḍanīti", "schools": {"mimamsa": "endorsed"},
     "definition": "The science of governance and punishment; use of the royal sceptre to maintain order.",
     "source": "Arthaśāstra 1.4"},
    {"id": "sadharana_dharma", "label": "Sādhāraṇa Dharma", "type": "SocialConcept",
     "sanskrit": "sādhāraṇa dharma", "schools": {"all": "endorsed"},
     "definition": "Universal duties applying to all people regardless of varṇa or āśrama.",
     "source": "Manusmṛti 6.92"},
    {"id": "panchayajna",      "label": "Pañcamahāyajña",   "type": "SocialConcept",
     "sanskrit": "pañcamahāyajña", "schools": {"mimamsa": "endorsed"},
     "definition": "Five great sacrifices obligatory for householders: to Brahman, ancestors, gods, beings, and guests.",
     "source": "Manusmṛti 3.69-70"},

    # ── RITUAL / MĪMĀṂSĀ ─────────────────────────────────────────
    {"id": "nitya_karma",      "label": "Nitya Karma",      "type": "RitualConcept",
     "sanskrit": "nitya karma", "schools": {"mimamsa": "endorsed"},
     "definition": "Obligatory duties that must be performed daily without fail; omission incurs sin.",
     "source": "Mīmāṃsā Sūtras 4.1"},
    {"id": "naimittika_karma", "label": "Naimittika Karma", "type": "RitualConcept",
     "sanskrit": "naimittika karma", "schools": {"mimamsa": "endorsed"},
     "definition": "Occasional obligatory rites performed on specific occasions (birth, death, eclipses, etc.).",
     "source": "Mīmāṃsā Sūtras 4.2"},
    {"id": "kamya_karma",      "label": "Kāmya Karma",      "type": "RitualConcept",
     "sanskrit": "kāmya karma", "schools": {"mimamsa": "endorsed"},
     "definition": "Optional rites performed to fulfil specific desires; produce merit but also bondage.",
     "source": "Mīmāṃsā Sūtras 4.3"},
    {"id": "nisiddha_karma",   "label": "Niṣiddha Karma",   "type": "RitualConcept",
     "sanskrit": "niṣiddha karma", "schools": {"mimamsa": "endorsed"},
     "definition": "Prohibited actions; ritually or ethically forbidden acts whose performance incurs sin.",
     "source": "Mīmāṃsā Sūtras 4.4"},
    {"id": "yajna",            "label": "Yajña",            "type": "RitualConcept",
     "sanskrit": "yajña", "schools": {"mimamsa": "endorsed", "advaita": "endorsed"},
     "definition": "Sacrifice or offering; ceremonial act of worship connecting the human and divine realms.",
     "source": "Bhagavad Gītā 3.9-16"},
    {"id": "shraddha_ritual",  "label": "Śrāddha",          "type": "RitualConcept",
     "sanskrit": "śrāddha", "schools": {"mimamsa": "endorsed"},
     "definition": "Ancestral rites; ritual offering of food and water to departed ancestors for their nourishment.",
     "source": "Manusmṛti 3.122-286"},
    {"id": "upanayana",        "label": "Upanayana",        "type": "RitualConcept",
     "sanskrit": "upanayana", "schools": {"mimamsa": "endorsed"},
     "definition": "Sacred thread initiation; sacrament marking entry into the student stage for dvija varṇas.",
     "source": "Manusmṛti 2.36-65"},
    {"id": "sandhyavandana",   "label": "Sandhyāvandana",   "type": "RitualConcept",
     "sanskrit": "sandhyāvandana", "schools": {"mimamsa": "endorsed"},
     "definition": "Twilight worship; thrice-daily obligatory rites of prayer, water-offering and Gāyatrī repetition.",
     "source": "Manusmṛti 2.101-102"},

    # ── TEXTS / PRAMĀṆA-TEXTS ───────────────────────────────────
    {"id": "vedas",            "label": "Vedas",            "type": "TextualConcept",
     "sanskrit": "veda", "schools": {"all": "endorsed"},
     "definition": "The four sacred scriptures (Ṛg, Sāma, Yajur, Atharva); the highest textual authority in Hinduism.",
     "source": "Manusmṛti 2.6"},
    {"id": "upanishads",       "label": "Upaniṣads",        "type": "TextualConcept",
     "sanskrit": "upaniṣad", "schools": {"advaita": "endorsed", "vishishtadvaita": "endorsed", "dvaita": "endorsed"},
     "definition": "The philosophical culmination of the Vedas (Vedānta); 108 texts focused on knowledge of Brahman.",
     "source": "Muṇḍaka Upaniṣad 3.2.6"},
    {"id": "brahma_sutras",    "label": "Brahma Sūtras",    "type": "TextualConcept",
     "sanskrit": "brahma sūtra", "schools": {"advaita": "endorsed", "vishishtadvaita": "endorsed", "dvaita": "endorsed"},
     "definition": "Systematized aphorisms by Bādarāyaṇa synthesizing Upaniṣadic teachings; debated by all Vedānta schools.",
     "source": "Brahma Sūtras 1.1.1"},
    {"id": "bhagavad_gita",    "label": "Bhagavad Gītā",    "type": "TextualConcept",
     "sanskrit": "bhagavad gītā", "schools": {"all": "endorsed"},
     "definition": "The divine song of 700 verses; Krishna's teaching to Arjuna synthesizing all paths and schools.",
     "source": "Mahābhārata Bhīṣma Parva 25-42"},
    {"id": "manusmriti",       "label": "Manusmṛti",        "type": "TextualConcept",
     "sanskrit": "manusmṛti", "schools": {"mimamsa": "endorsed"},
     "definition": "Laws of Manu; authoritative Dharmaśāstra text on social duties, governance, and righteousness.",
     "source": "Manusmṛti 1.1"},
    {"id": "arthashastra",     "label": "Arthaśāstra",      "type": "TextualConcept",
     "sanskrit": "arthaśāstra", "schools": {"mimamsa": "endorsed"},
     "definition": "Kauṭilya's political economy treatise on governance, statecraft, and economic policy.",
     "source": "Arthaśāstra 1.1.1"},
    {"id": "yoga_sutras",      "label": "Yoga Sūtras",      "type": "TextualConcept",
     "sanskrit": "yoga sūtra", "schools": {"nyaya": "endorsed"},
     "definition": "Patañjali's 196 aphorisms systematizing classical yoga; foundation of Rāja Yoga.",
     "source": "Yoga Sūtras 1.1"},
    {"id": "puranas",          "label": "Purāṇas",          "type": "TextualConcept",
     "sanskrit": "purāṇa", "schools": {"bhakti": "endorsed", "vishishtadvaita": "endorsed"},
     "definition": "The 18 Mahāpurāṇas; vast encyclopaedic texts on cosmology, mythology, dharma, and devotion.",
     "source": "Bhāgavata Purāṇa 1.1.1"},
    {"id": "nyaya_sutras",     "label": "Nyāya Sūtras",     "type": "TextualConcept",
     "sanskrit": "nyāya sūtra", "schools": {"nyaya": "endorsed"},
     "definition": "Gautama's foundational text of the Nyāya school; systematizes logic, debate, and epistemology.",
     "source": "Nyāya Sūtras 1.1.1"},
    {"id": "mimamsa_sutras",   "label": "Mīmāṃsā Sūtras",  "type": "TextualConcept",
     "sanskrit": "mīmāṃsā sūtra", "schools": {"mimamsa": "endorsed"},
     "definition": "Jaimini's systematic treatise on Vedic exegesis and the primacy of ritual injunctions.",
     "source": "Mīmāṃsā Sūtras 1.1.1"},

    # ── LIBERATION PHILOSOPHY ────────────────────────────────────
    {"id": "moksha",           "label": "Mokṣa",            "type": "SoteriologicalConcept",
     "sanskrit": "mokṣa", "schools": {"all": "endorsed"},
     "definition": "Liberation from the cycle of rebirth; the fourth and supreme goal of human life.",
     "source": "Bhagavad Gītā 18.66"},
    {"id": "dharma",           "label": "Dharma",           "type": "EthicalConcept",
     "sanskrit": "dharma", "schools": {"all": "endorsed"},
     "definition": "Cosmic order, duty, righteousness; the first of four purushārthas guiding righteous living.",
     "source": "Manusmṛti 2.6"},
    {"id": "artha",            "label": "Artha",            "type": "SocialConcept",
     "sanskrit": "artha", "schools": {"mimamsa": "endorsed"},
     "definition": "Material wealth, power, and prosperity; the second purushārtha, legitimate when pursued within dharma.",
     "source": "Arthaśāstra 1.2.9"},
    {"id": "purushartha",      "label": "Puruṣārtha",       "type": "EthicalConcept",
     "sanskrit": "puruṣārtha", "schools": {"all": "endorsed"},
     "definition": "The four aims of human life: dharma, artha, kāma, and mokṣa.",
     "source": "Manusmṛti 2.224"},
    {"id": "nishkama_karma",   "label": "Niṣkāma Karma",    "type": "EthicalConcept",
     "sanskrit": "niṣkāma karma", "schools": {"advaita": "endorsed", "bhakti": "endorsed"},
     "definition": "Desireless action; performing duty without attachment to its fruits, as taught in the Gītā.",
     "source": "Bhagavad Gītā 3.19"},
    {"id": "karma",            "label": "Karma",            "type": "MetaphysicalConcept",
     "sanskrit": "karma", "schools": {"all": "endorsed"},
     "definition": "Action and its cosmic consequence; the inexorable law connecting intention, deed, and result.",
     "source": "Bṛhadāraṇyaka Upaniṣad 4.4.5"},
    {"id": "sanchita_karma",   "label": "Sañcita Karma",    "type": "MetaphysicalConcept",
     "sanskrit": "sañcita karma", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "Accumulated karma from all past lives; the entire stock of unmanifested karmic seeds.",
     "source": "Vivekacūḍāmaṇi 453"},
    {"id": "prarabdha_karma",  "label": "Prārabdha Karma",  "type": "MetaphysicalConcept",
     "sanskrit": "prārabdha karma", "schools": {"advaita": "endorsed", "nyaya": "endorsed"},
     "definition": "Karma that has begun to fructify in the current life; cannot be averted even by the liberated.",
     "source": "Vivekacūḍāmaṇi 454"},
    {"id": "agami_karma",      "label": "Āgāmi Karma",      "type": "MetaphysicalConcept",
     "sanskrit": "āgāmi karma", "schools": {"advaita": "endorsed"},
     "definition": "Karma being created in the present life; fresh impressions from current actions.",
     "source": "Vivekacūḍāmaṇi 452"},
]


# ─────────────────────────────────────────────────────────────────
# EXPANDED SCHOOL STANCES + DEBATE NODES
# ─────────────────────────────────────────────────────────────────

SCHOOL_DEBATE_NODES = [
    {"id": "brahman_world_relation", "label": "Brahman–World Relation", "type": "DebateNode",
     "definition": "How the empirical world relates to ultimate reality; core metaphysical debate.",
     "schools": {"advaita": "vivartavāda (apparent transformation)",
                 "vishishtadvaita": "pariṇāmavāda (real transformation)",
                 "dvaita": "svabhāvika bhedavāda (eternal real difference)"}},
    {"id": "jiva_brahman_relation",  "label": "Jīva–Brahman Relation",  "type": "DebateNode",
     "definition": "Whether the individual self is identical to, part of, or different from Brahman.",
     "schools": {"advaita": "identical (ahaṃ brahmāsmi)",
                 "vishishtadvaita": "part-whole (aṃśa-aṃśi)",
                 "dvaita": "eternally different (nitya bhinnatva)"}},
    {"id": "vedic_authority_scope",  "label": "Vedic Authority",        "type": "DebateNode",
     "definition": "Whether Vedas are eternal (nitya), self-valid, and whose scope covers ritual vs. knowledge.",
     "schools": {"mimamsa": "Vedas are nitya, apauruṣeya; karmakāṇḍa primary",
                 "advaita": "Vedas are apauruṣeya; jñānakāṇḍa (Upaniṣads) supreme",
                 "nyaya": "Vedas have validity because authored by omniscient God"}},
    {"id": "god_world_causality",    "label": "God–World Causality",    "type": "DebateNode",
     "definition": "Whether God is the efficient cause, material cause, or both of the universe.",
     "schools": {"advaita": "Brahman is both but world is apparent (vivarta)",
                 "vishishtadvaita": "Brahman is both; world is real body of God",
                 "dvaita": "God is efficient cause; matter is separate",
                 "nyaya": "God is only efficient cause; atoms eternal"}},
    {"id": "liberation_nature",      "label": "Nature of Liberation",   "type": "DebateNode",
     "definition": "What liberation actually consists in — identity, proximity, or blissful worship.",
     "schools": {"advaita": "cessation of apparent difference; pure consciousness",
                 "vishishtadvaita": "eternal blissful service to Brahman in Vaikuṇṭha",
                 "dvaita": "eternal blissful worship of Viṣṇu while remaining distinct",
                 "bhakti": "eternal loving service (sevā) in the divine realm"}},
]


def expand_kg(g: HPOGraph) -> dict:
    """Add 200+ new nodes to the HPO Knowledge Graph using the proper HPOGraph API."""
    before = g.nx_graph.number_of_nodes()
    added = 0
    skipped = 0

    for c in EXTENDED_CONCEPTS:
        nid = c["id"]
        if g.nx_graph.has_node(nid):
            skipped += 1
            continue

        # Add concept via proper API
        g.add_concept(
            concept_id=nid,
            label=c["label"],
            concept_type=c["type"],
            definition=c.get("definition", ""),
            sanskrit=c.get("sanskrit", ""),
            related_texts=[c.get("source", "")] if c.get("source") else []
        )

        # Add school stance edges using nx_graph directly
        for school_id, stance in c.get("schools", {}).items():
            if school_id == "all":
                for s in ["advaita", "dvaita", "nyaya", "mimamsa", "vishishtadvaita", "bhakti"]:
                    if g.nx_graph.has_node(s):
                        g.nx_graph.add_edge(s, nid, predicate="hasStanceOn", stance="endorsed")
                        g.rdf_graph.add((BASE[s], HPO["hasStanceOn"], BASE[nid]))
            elif g.nx_graph.has_node(school_id):
                g.nx_graph.add_edge(school_id, nid, predicate="hasStanceOn", stance=stance)
                g.rdf_graph.add((BASE[school_id], HPO["hasStanceOn"], BASE[nid]))

        added += 1

    # Add debate nodes
    for d in SCHOOL_DEBATE_NODES:
        nid = d["id"]
        if not g.nx_graph.has_node(nid):
            g.add_concept(
                concept_id=nid,
                label=d["label"],
                concept_type=d["type"],
                definition=d.get("definition", ""),
            )
            for school_id, stance_desc in d.get("schools", {}).items():
                if g.nx_graph.has_node(school_id):
                    g.nx_graph.add_edge(school_id, nid,
                        predicate="hasPositionOn",
                        description=stance_desc)
                    g.rdf_graph.add((BASE[school_id], HPO["hasPositionOn"], BASE[nid]))
            added += 1

    after = g.nx_graph.number_of_nodes()
    return {"added": added, "skipped": skipped,
            "nodes_before": before, "nodes_after": after}


if __name__ == "__main__":
    from kg.populate_kg import populate
    g = HPOGraph()
    populate(g)
    result = expand_kg(g)
    print(f"\nKG Expansion Complete")
    print(f"  Nodes before  : {result['nodes_before']}")
    print(f"  Nodes added   : {result['added']}")
    print(f"  Nodes skipped : {result['skipped']} (already present)")
    print(f"  Nodes after   : {result['nodes_after']}")
    print(f"  Edges total   : {g.nx_graph.number_of_edges()}")

    # Save expanded KG stats
    out = Path(__file__).parent / "kg_expansion_stats.json"
    out.write_text(json.dumps(result, indent=2))
    print(f"\nStats saved to {out}")
